@extends('layouts.navframe')
@section('page_heading','Credentials')
@section('section')

        <!-- /.row -->
        <div class="col-sm-12">
        <!-- /.row -->

        <div class="row">
            <div class="col-sm-12">
                <div class="alert alert-info " role="alert">
                    <h3 style="margin-top:0px;"><i class="fa fa-info-circle"></i> Alert</h3> 
                    A new key pair may be generated at any time but you must if you suspect that your credentials have been compromised. The new public key must be shared with all your partners before transactions can be received and processed. Sending transactions to partners will not be impacted. <br/><b>Reminder: Never share the private key.</b>
                </div>
            </div>
        </div>

        <div class="row"> <!-- START Form Row -->
            <div class="col-lg-6">
                <!-- Generate New Key Pair panel  - ONLY ALLOW UPLOAD-->
                <!--
                <div id="pnl-generatenewkeypair" class="panel panel-default">
                    <div class="panel-heading">
                        <h3 class="panel-title">Generate a New Key Pair:</h3>
                    </div>
            
                    <div class="panel-body">
                        <form role="form" method="POST" action="/credentials/confchngmstrpwd">
                        {{ csrf_field() }}
                            <div class="form-group">
                                <label>Passphrase:</label>
                                <input id="txt-passphrase" name="passphrase" type="text" class="form-control" placeholder="">
                            </div>

                            <div class="form-group">
                                <button id="btn-generatenewkeypair" name="submit" value="newkeypair" type="submit" class="btn btn-success">Generate New Key Pair</button>
                                <button id="btn-cnclnewkeypair" type="button" class="btn btn-danger">Cancel</button>
                            </div>
                        </form>
                        {{-- Display errors generated by the validator --}}
                        @if (count($errors) > 0)
                        <!-- ./ Error div -->
                        <div id="div-errors" class="alert alert-danger">
                            <div class="list-group" style="margin-bottom:0px;">
                                @foreach ($errors->all() as $error)
                                <span class="list-group-item">{{ $error }}</span>
                                @endforeach
                            </div>
                        </div> <!-- ./ Error div -->
                        @endif
                    </div>
                </div> 
                -->
                <!-- End Generate New Key Pair panel -->
                <!-- Upload New Key Pair panel -->
                <div id="pnl-uploadnewpubkey" class="panel panel-default">
                    <div class="panel-heading">
                        <h3 class="panel-title">Upload a New Public Key:</h3>
                    </div>
            
                    <div class="panel-body">
                        <form role="form" method="POST" action="/credentials/uploadpubkeyfile" enctype="multipart/form-data">
                        {{ csrf_field() }}
                            <div class="form-group">
                                <label>Choose a .pem file:</label>
                                <input id="" name="pubkeyfile" type="file" class="form-control" placeholder="">
                            </div>

                            <div class="form-group">
                                <button id="btn-uploadnewpubkey" name="submit" value="uploadnewpubkey" type="submit" class="btn btn-success">Upload New Public Key</button>
                                <button id="btn-cnclnewkeypair" type="button" class="btn btn-danger">Cancel</button>
                            </div>
                        </form>
                        {{-- Display errors generated by the validator --}}
                        @if (count($errors) > 0)
                        <!-- ./ Error div -->
                        <div id="div-errors" class="alert alert-danger">
                            <div class="list-group" style="margin-bottom:0px;">
                                @foreach ($errors->all() as $error)
                                <span class="list-group-item">{{ $error }}</span>
                                @endforeach
                            </div>
                        </div> <!-- ./ Error div -->
                        @endif
                    </div>
                </div> <!-- End Upload New Key Pair panel -->
            </div> <!-- /.col-lg-6 -->
        </div> <!-- END Form Row -->
        
        @stop
