@extends('layouts.navframe')
@section('page_heading','Credentials')
@section('section')

        <!-- /.row -->
        <div class="col-sm-12">
        <!-- /.row -->

        <div class="row">
            <div class="col-sm-12">
                <div class="alert alert-info " role="alert">
                    <h3 style="margin-top:0px;"><i class="fa fa-info-circle"></i> Alert</h3> 
                    A new API Key and a new Master Password should be generated periodically to increase security. At any time if you suspect that your credentials have been compromised generate new credentials immediately. It is stating the obvious that you should not share your credentials with anyone other than authorized users. When using the API Key in an application store it as a hash not in clear text. 
                </div>
            </div>
        </div>

        <div class="row"> <!-- START Form Row -->
            <div class="col-lg-6">
                <!-- Form -->
                <div id="pnl-entercredentials" class="panel panel-default">
                    <div class="panel-heading">
                        <h3 class="panel-title">Enter Credentials</h3>
                    </div>
            
                    <div class="panel-body">
                        <form role="form" method="POST" action="/credentials/validate">
                            {{ csrf_field() }}
                            <div class="form-group">
                                <label>Remitter Id:</label>
                                <input id="fld-remitterid" class="form-control" placeholder="" name="remitter_id" value="475246">
                            </div>

                            <div class="form-group">`
                                <label>Master Password:</label>
                                <input id="fld-mstrpwd" class="form-control" placeholder="" name="master_password" value="boardwalk" type="password">
                            </div>

                            <div class="form-group">
                                <label>Current API Key:</label>
                                <input id="fld-apikey" class="form-control" placeholder="" name="api_key" value="b32ca72b-ace3-41f6-9cc4-b8f5fcc8eca6">
                            </div>

                            <div class="form-group">
                                <button id="btn-newapikey" name="submit" value="newapikey" type="submit" class="btn btn-primary">New API Key</button>
                                <button id="btn-chngmstrpwd" name="submit" value="chngmstrpwd" type="submit" class="btn btn-primary">Change Master Password</button>
                                <button id="btn-newkeypair" name="submit" value="newkeypair" type="submit" class="btn btn-primary">New Key Pair</button>
                            </div>
                        </form>
                        
                        {{-- Display errors generated by the validator --}}
                        @if (count($errors) > 0)
                        <!-- ./ Error div -->
                        <div id="div-errors" class="alert alert-danger">
                            <div class="list-group" style="margin-bottom:0px;">
                                @foreach ($errors->all() as $error)
                                <span class="list-group-item">{{ $error }}</span>
                                @endforeach
                            </div>
                        </div> <!-- ./ Error div -->
                        @endif
                    </div>
                </div> <!-- ./ Form Panel -->
            </div> <!-- /.col-lg-6 -->
        </div> <!-- END Form Row -->
        
        @stop
