@extends('layouts.navframe')
@section('page_heading','Settings and Preferences')
@section('section')

        <!-- /.row -->
        <div class="col-sm-12">
        <!-- /.row -->

        <form role="form" method="POST" action="/settings">
        {{ csrf_field() }}
        <div class="row"> <!-- START Form Row -->
            <div class="col-lg-6">
                <!-- Form -->
                <div id="pnl-currencypreferences" class="panel panel-default">
                    <div class="panel-heading">
                        <h3 class="panel-title">Currency Preferences</h3>
                    </div>
            
                    <div class="panel-body">
                            <div class="form-group">
                                <label>Billing Currency:</label>
                                <select class="form-control">
                                    <option>US Dollar (USD)</option>
                                    <option>Euro (EUR)</option>
                                    <option>Pound Sterling GBP)</option>
                                    <option>Indian Rupee (INR)</option>
                                    <option>Chinese Yuan (CNY)</option>
                                </select> 
                                <span>All billing amounts will be displayed in USD and this currency.</span>
                            </div>
                    </div>
                </div> <!-- ./ Form Panel -->
            </div> <!-- /.col-lg-6 -->
        </div> <!-- END Form Row -->

        <div class="row"> <!-- START Second Row -->
            <div class="col-lg-6">
                <!-- Form -->
                <div id="pnl-contactpreferences" class="panel panel-default">
                    <div class="panel-heading">
                        <h3 class="panel-title">Contact Preferences</h3>
                    </div>
            
                    <div class="panel-body">
                            <div class="form-group">
                                <label>Primary Email Id:</label>
                                <input id="fld-primarycontact" class="form-control" placeholder="" name="primary_contact" value="">
                                <span>All information will be sent to this email id.</span>
                            </div>
                            <div class="form-group">
                                <label>Billing Email Id:</label>
                                <input id="fld-billingcontact" class="form-control" placeholder="" name="billing_contact" value="">
                                <span>All billing information will be sent to this email id.</span>
                            </div>
                            <div class="form-group">
                                <label>Operations Email Id:</label>
                                <input id="fld-operationscontact" class="form-control" placeholder="" name="operations_contact" value="">
                                <span>All operational information will be sent to this email id.</span>
                            </div>
                            <div class="form-group">
                                <label>Technical Email Id:</label>
                                <input id="fld-technicalcontact" class="form-control" placeholder="" name="technical_contact" value="">
                                <span>All technical information will be sent to this email id.</span>
                            </div>
                            <div class="form-group">
                                <label>Security Email Id:</label>
                                <input id="fld-securitycontact" class="form-control" placeholder="" name="security_contact" value="">
                                <span>All operational information will be sent to this email id.</span>
                            </div>
                    </div>
                </div> <!-- ./ Form Panel -->
            </div> <!-- /.col-lg-6 -->
        </div> <!-- END Second Row -->

        <div class="row"> <!-- START Form Row -->
            <div class="col-lg-12">
                <div class="form-group">
                    <button id="btn-update" name="submit" value="update" type="submit" class="btn btn-success">Update</button>
                    <button id="btn-reset" name="submit" value="reset" type="submit" class="btn btn-warning">Reset</button>
                    <button id="btn-cancel" name="submit" value="cancel" type="submit" class="btn btn-danger">Cancel</button>
                </div>
        
                {{-- Display errors generated by the validator --}}
                @if (count($errors) > 0)
                <!-- ./ Error div -->
                <div id="div-errors" class="alert alert-danger">
                <div class="list-group" style="margin-bottom:0px;">
                @foreach ($errors->all() as $error)
                <span class="list-group-item">{{ $error }}</span>
                @endforeach
                </div>
                </div> <!-- ./ Error div -->
                @endif
            </div>
        </div>
        </form>
        
        @stop
